# How to use it
# make all
# make dependencies
# make run path="AbsolutePath/MixedFilesTestData"

dependencies:
	pip install -r requirements.txt
run:
	python3 static.py $(path)
all:
	pip install -r requirements.txt
	python3 static.py $(path)